version: "3"

services:
  web:
    image: nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - $NGINX_PORT
    volumes:
      - "./drupal/web:/var/www/html"
      - "./drupal/nginx.conf:/etc/nginx/conf.d/default.conf"    
    depends_on:
      - php    
    labels:
      - 'traefik.backend=${PROJECT_NAME}_nginx'
      - "traefik.port=${NGINX_PORT}"
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  php:
    image: drupal:$DRUPAL_TAG
    container_name: "${PROJECT_NAME}_drupal"
    volumes:
      - "./drupal/web:/var/www/html"
    restart: always
    depends_on:
      - mysql    

  mysql:
      platform: linux/x86_64 # add this when you are working on ARM cpu
      image: mysql:$MYSQL_TAG
      container_name: "${PROJECT_NAME}_mysql"
      # ports:
        # - $DB_PORT
      entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
      environment:
        MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        MYSQL_USER: $DB_USER
        MYSQL_PASSWORD: $DB_PASSWORD
        MYSQL_DATABASE: $DB_NAME
      volumes:
        - "./drupal/mysql:/var/lib/mysql"
      restart: always

  # portainer:
    # image: portainer/portainer
    # container_name: "${PROJECT_NAME}_portainer"
    # command: --no-auth -H unix:///var/run/docker.sock
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
    # labels:
      # - 'traefik.backend=${PROJECT_NAME}_portainer'
      # - 'traefik.port=9000'
      # - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'

  # traefik:
    # image: traefik
    # container_name: "${PROJECT_NAME}_traefik"
    # command: -c /dev/null --web --docker --logLevel=INFO
    # ports:
      # - '8080:80'
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
